name: Black Check

on: workflow_dispatch

jobs:
  black_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --exclude '^\\..*|^.*/migrations/.*|virtualenv/.*|.*\\.html$|.*\\.css$|.*\\.xml$|.*\\.yml'"
          version: "~= 23.1.0"
