name: Check migrations

on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  commit-name-check:
    runs-on: ubuntu-latest

    steps:
      - name: Commit name check
        run: |
          echo "${{ github.event }}"
          if contains(${{ github.event.head_commit.message }}, , "merge branch"); then
            echo "IS_MERGE_COMMIT='true'" >> $GITHUB_ENV
          else
            echo "IS_MERGE_COMMIT='false'" >> $GITHUB_ENV      
            exit 0
          fi
        

  migration-check:
    runs-on: ubuntu-latest
    needs: commit-name-check
    if: ${{ env.IS_MERGE_COMMIT }} == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check migrations
      run: |
        python manage.py makemigrations --check --dry-run

    - name: Validate migrations
      run: |
        python manage.py migrate --check
