name: Check Django Migrations

on:
  pull_request:
    paths:
      - '**/*.py'  # Adjust the path pattern based on your Django project structure

jobs:
  migration-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust the path to your requirements file

    - name: Check migrations
      run: |
        python manage.py makemigrations --check --dry-run

    - name: Validate migrations
      run: |
        python manage.py migrate --check
