name: Update Branch Before Merge

on: push

jobs:
  update-before-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update branch with changes from base
      run: |
        git fetch origin
        git checkout origin/main
        git pull origin main
        git checkout -
        git merge --no-ff $ origin/main -m "Merge changes from base branch"


        # Handle merge conflicts
        if [ $? -ne 0 ]; then
          # Handle conflicts (e.g., use a merge tool, manual resolution, etc.)
          # Then continue with the merge
          git merge --continue
        fi
