name: Update Branch Before Merge

on:
  pull_request:
    branches:    
      - 'main'
    types: [created, edited]

jobs:
  update-before-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update branch with changes from base
      run: |
        git checkout main
        git pull
        git checkout -
        git merge --no-ff $ main -m "Merge changes from base branch"


        # Handle merge conflicts
        if [ $? -ne 0 ]; then
          # Handle conflicts (e.g., use a merge tool, manual resolution, etc.)
          # Then continue with the merge
          git merge --continue
        fi
