name: Manually rollback
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
      choice:
        type: multi-choice
        description: Make a choice
        options:
        - foo
        - bar
        - TEST_IP

jobs:
  Rollback:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.TEST_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: aha
        run: |
          echo "Using API key: $API_KEY"
          echo ${API_KEY}
          
 
